/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAffirmationsRouteImport } from './routes/_authenticated/affirmations'
import { Route as AuthenticatedBadgesRouteImport } from './routes/_authenticated/badges'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedCheckInRouteImport } from './routes/_authenticated/check-in'
import { Route as AuthenticatedFlagsRouteImport } from './routes/_authenticated/flags'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedLettersRouteImport } from './routes/_authenticated/letters'
import { Route as AuthenticatedPicturesRouteImport } from './routes/_authenticated/pictures'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedQuestionnaireRouteImport } from './routes/_authenticated/questionnaire'
import { Route as AuthenticatedRitualsRouteImport } from './routes/_authenticated/rituals'
import { Route as AuthenticatedTriggersRouteImport } from './routes/_authenticated/triggers'
import { Route as AuthenticatedWinsRouteImport } from './routes/_authenticated/wins'
import { Route as ApiPublicHooksEveningRemindersRouteImport } from './routes/api/public/hooks/evening-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffirmationsRoute =
  AuthenticatedAffirmationsRouteImport.update({
    id: '/affirmations',
    path: '/affirmations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBadgesRoute = AuthenticatedBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInRoute = AuthenticatedCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlagsRoute = AuthenticatedFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLettersRoute = AuthenticatedLettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPicturesRoute = AuthenticatedPicturesRouteImport.update({
  id: '/pictures',
  path: '/pictures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionnaireRoute =
  AuthenticatedQuestionnaireRouteImport.update({
    id: '/questionnaire',
    path: '/questionnaire',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRitualsRoute = AuthenticatedRitualsRouteImport.update({
  id: '/rituals',
  path: '/rituals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTriggersRoute = AuthenticatedTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWinsRoute = AuthenticatedWinsRouteImport.update({
  id: '/wins',
  path: '/wins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksEveningRemindersRoute =
  ApiPublicHooksEveningRemindersRouteImport.update({
    id: '/api/public/hooks/evening-reminders',
    path: '/api/public/hooks/evening-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/affirmations': typeof AuthenticatedAffirmationsRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/flags': typeof AuthenticatedFlagsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/letters': typeof AuthenticatedLettersRoute
  '/pictures': typeof AuthenticatedPicturesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/questionnaire': typeof AuthenticatedQuestionnaireRoute
  '/rituals': typeof AuthenticatedRitualsRoute
  '/triggers': typeof AuthenticatedTriggersRoute
  '/wins': typeof AuthenticatedWinsRoute
  '/api/public/hooks/evening-reminders': typeof ApiPublicHooksEveningRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/affirmations': typeof AuthenticatedAffirmationsRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/flags': typeof AuthenticatedFlagsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/letters': typeof AuthenticatedLettersRoute
  '/pictures': typeof AuthenticatedPicturesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/questionnaire': typeof AuthenticatedQuestionnaireRoute
  '/rituals': typeof AuthenticatedRitualsRoute
  '/triggers': typeof AuthenticatedTriggersRoute
  '/wins': typeof AuthenticatedWinsRoute
  '/api/public/hooks/evening-reminders': typeof ApiPublicHooksEveningRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/affirmations': typeof AuthenticatedAffirmationsRoute
  '/_authenticated/badges': typeof AuthenticatedBadgesRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/check-in': typeof AuthenticatedCheckInRoute
  '/_authenticated/flags': typeof AuthenticatedFlagsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/letters': typeof AuthenticatedLettersRoute
  '/_authenticated/pictures': typeof AuthenticatedPicturesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/questionnaire': typeof AuthenticatedQuestionnaireRoute
  '/_authenticated/rituals': typeof AuthenticatedRitualsRoute
  '/_authenticated/triggers': typeof AuthenticatedTriggersRoute
  '/_authenticated/wins': typeof AuthenticatedWinsRoute
  '/api/public/hooks/evening-reminders': typeof ApiPublicHooksEveningRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/paywall'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/activity'
    | '/affirmations'
    | '/badges'
    | '/change-password'
    | '/check-in'
    | '/flags'
    | '/home'
    | '/journal'
    | '/letters'
    | '/pictures'
    | '/profile'
    | '/questionnaire'
    | '/rituals'
    | '/triggers'
    | '/wins'
    | '/api/public/hooks/evening-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/paywall'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/activity'
    | '/affirmations'
    | '/badges'
    | '/change-password'
    | '/check-in'
    | '/flags'
    | '/home'
    | '/journal'
    | '/letters'
    | '/pictures'
    | '/profile'
    | '/questionnaire'
    | '/rituals'
    | '/triggers'
    | '/wins'
    | '/api/public/hooks/evening-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/paywall'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/activity'
    | '/_authenticated/affirmations'
    | '/_authenticated/badges'
    | '/_authenticated/change-password'
    | '/_authenticated/check-in'
    | '/_authenticated/flags'
    | '/_authenticated/home'
    | '/_authenticated/journal'
    | '/_authenticated/letters'
    | '/_authenticated/pictures'
    | '/_authenticated/profile'
    | '/_authenticated/questionnaire'
    | '/_authenticated/rituals'
    | '/_authenticated/triggers'
    | '/_authenticated/wins'
    | '/api/public/hooks/evening-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PaywallRoute: typeof PaywallRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHooksEveningRemindersRoute: typeof ApiPublicHooksEveningRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affirmations': {
      id: '/_authenticated/affirmations'
      path: '/affirmations'
      fullPath: '/affirmations'
      preLoaderRoute: typeof AuthenticatedAffirmationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/badges': {
      id: '/_authenticated/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AuthenticatedBadgesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in': {
      id: '/_authenticated/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthenticatedCheckInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flags': {
      id: '/_authenticated/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof AuthenticatedFlagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/letters': {
      id: '/_authenticated/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof AuthenticatedLettersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pictures': {
      id: '/_authenticated/pictures'
      path: '/pictures'
      fullPath: '/pictures'
      preLoaderRoute: typeof AuthenticatedPicturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questionnaire': {
      id: '/_authenticated/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof AuthenticatedQuestionnaireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rituals': {
      id: '/_authenticated/rituals'
      path: '/rituals'
      fullPath: '/rituals'
      preLoaderRoute: typeof AuthenticatedRitualsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/triggers': {
      id: '/_authenticated/triggers'
      path: '/triggers'
      fullPath: '/triggers'
      preLoaderRoute: typeof AuthenticatedTriggersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wins': {
      id: '/_authenticated/wins'
      path: '/wins'
      fullPath: '/wins'
      preLoaderRoute: typeof AuthenticatedWinsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/evening-reminders': {
      id: '/api/public/hooks/evening-reminders'
      path: '/api/public/hooks/evening-reminders'
      fullPath: '/api/public/hooks/evening-reminders'
      preLoaderRoute: typeof ApiPublicHooksEveningRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAffirmationsRoute: typeof AuthenticatedAffirmationsRoute
  AuthenticatedBadgesRoute: typeof AuthenticatedBadgesRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCheckInRoute: typeof AuthenticatedCheckInRoute
  AuthenticatedFlagsRoute: typeof AuthenticatedFlagsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedLettersRoute: typeof AuthenticatedLettersRoute
  AuthenticatedPicturesRoute: typeof AuthenticatedPicturesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuestionnaireRoute: typeof AuthenticatedQuestionnaireRoute
  AuthenticatedRitualsRoute: typeof AuthenticatedRitualsRoute
  AuthenticatedTriggersRoute: typeof AuthenticatedTriggersRoute
  AuthenticatedWinsRoute: typeof AuthenticatedWinsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAffirmationsRoute: AuthenticatedAffirmationsRoute,
  AuthenticatedBadgesRoute: AuthenticatedBadgesRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCheckInRoute: AuthenticatedCheckInRoute,
  AuthenticatedFlagsRoute: AuthenticatedFlagsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedLettersRoute: AuthenticatedLettersRoute,
  AuthenticatedPicturesRoute: AuthenticatedPicturesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuestionnaireRoute: AuthenticatedQuestionnaireRoute,
  AuthenticatedRitualsRoute: AuthenticatedRitualsRoute,
  AuthenticatedTriggersRoute: AuthenticatedTriggersRoute,
  AuthenticatedWinsRoute: AuthenticatedWinsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PaywallRoute: PaywallRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiPublicHooksEveningRemindersRoute: ApiPublicHooksEveningRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
